version: 2.1
jobs:
  build:
    working_directory: ~/rex12
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: circleci/ruby:2.5.1

    steps:
    - checkout
    # Restore the dependency cache
    - restore_cache:
        keys:
        # We can share gems between branches if the Gemfile.lock has the same checksum (.ie nothing's new in it)
        - gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
    - run:
        name: Bundle Install
        command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
    # Save dependency cache
    - save_cache:
        key: gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle
        - ~/.bundle
    - run:
        name: Rspec Unit Tests
        no_output_timeout: 20m
        command: bundle exec rspec --require spec_helper --format RspecJunitFormatter --out /tmp/circle-tests/rspec/rspec.xml --format progress spec
    - store_test_results:
        path: /tmp/circle-tests
    - store_artifacts:
        path: /tmp/circle-tests

workflows:
  version: 2
  workflow:
    jobs:
    - build